name: Build, Publish, Deploy

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: halp-1000   # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: halp1000.azurecr.io
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - run: |
        docker build . -t halp1000.azurecr.io/${{ AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}
        docker push halp1000.azurecr.io/${{ AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'halp1000.azurecr.io/${{ AZURE_FUNCTIONAPP_NAME }}:${{ github.sha }}'